app:
    resource: '@AppBundle/Controller/'
    type: annotation

routing.insert:
    path:      /insert
    defaults:  { _controller: 'FabianPiconeDev\Web\Controller\ChitInsertionController:showInsertForm' }